In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import joblib

In [8]:
##Step1: Load Dataset

dataframe = pd.read_csv("csv/dataset.csv")

dataframe

             Label   area_0  area_1  area_2  area_3  area_4
0      Parasitized  15461.0   122.0     0.0     0.0     0.0
1      Parasitized  19438.0   164.5     0.0     0.0     0.0
2      Parasitized  15475.0    92.5    36.5     0.0     0.0
3      Parasitized  14063.0   211.0    51.5    11.0    10.5
4      Parasitized  13885.0     0.0     0.0     0.0     0.0
...            ...      ...     ...     ...     ...     ...
27553   Uninfected  13280.0     0.0     0.0     0.0     0.0
27554   Uninfected  12777.0     0.0     0.0     0.0     0.0
27555   Uninfected  14552.5     0.0     0.0     0.0     0.0
27556   Uninfected  16855.5     0.0     0.0     0.0     0.0
27557   Uninfected  18657.5     0.0     0.0     0.0     0.0

[27558 rows x 6 columns]

In [10]:
#Step2: Split into training and test data
x = dataframe.drop(["Label"],axis=1)
y = dataframe["Label"]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [5]:
x

        area_0  area_1  area_2  area_3  area_4
0      15461.0   122.0     0.0     0.0     0.0
1      19438.0   164.5     0.0     0.0     0.0
2      15475.0    92.5    36.5     0.0     0.0
3      14063.0   211.0    51.5    11.0    10.5
4      13885.0     0.0     0.0     0.0     0.0
...        ...     ...     ...     ...     ...
27553  13280.0     0.0     0.0     0.0     0.0
27554  12777.0     0.0     0.0     0.0     0.0
27555  14552.5     0.0     0.0     0.0     0.0
27556  16855.5     0.0     0.0     0.0     0.0
27557  18657.5     0.0     0.0     0.0     0.0

[27558 rows x 5 columns]

In [6]:
y

0        Parasitized
1        Parasitized
2        Parasitized
3        Parasitized
4        Parasitized
            ...
27553     Uninfected
27554     Uninfected
27555     Uninfected
27556     Uninfected
27557     Uninfected
Name: Label, Length: 27558, dtype: object

In [7]:
##Step4: Build a model
for i in range (100,1001,100):
    model = RandomForestClassifier(n_estimators=i,max_depth=5)
    model.fit(x_train,y_train)
    joblib.dump(model,"rf_malaria_2_"+str(i)+"_5")
    print("Model "+"rf_malaria_2_"+str(i)+"_5"+" prepared")

Model rf_malaria_2_100_5 prepared
Model rf_malaria_2_200_5 prepared
Model rf_malaria_2_300_5 prepared
Model rf_malaria_2_400_5 prepared
Model rf_malaria_2_500_5 prepared
Model rf_malaria_2_600_5 prepared
Model rf_malaria_2_700_5 prepared
Model rf_malaria_2_800_5 prepared
Model rf_malaria_2_900_5 prepared
Model rf_malaria_2_1000_5 prepared

In [1]:
##Step5: Make predictions and get classification report

for i in range (100,1001,100):
    print("For model with parameter "+str(i)+" and 5")
    model=joblib.load("rf_malaria_2_"+str(i)+"_5")
    predictions = model.predict(x_test)
    print(metrics.classification_report(predictions,y_test))
    print(model.score(x_test,y_test))
    print("\n\n\n")

For model with parameter 100 and 5

NameError: name 'joblib' is not defined